name: Release docker

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ vars.DOCKER_REGISTRY != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Docker
        uses: seepine/action-setup-docker@v1
        id: meta
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile
          tags: |
            ${{ vars.DOCKER_USERNAME }}/backend:${{ steps.meta.outputs.version }}
            ${{ vars.DOCKER_USERNAME }}/backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile.web
          tags: |
            ${{ vars.DOCKER_USERNAME }}/frontend:${{ steps.meta.outputs.version }}
            ${{ vars.DOCKER_USERNAME }}/frontend:latest

      - name: Success
        run: echo "Release success"

  ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Docker
        uses: seepine/action-setup-docker@v1
        id: meta
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.actor }}/backend:${{ steps.meta.outputs.version }}
            ghcr.io/${{ github.actor }}/backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile.web
          tags: |
            ghcr.io/${{ github.actor }}/frontend:${{ steps.meta.outputs.version }}
            ghcr.io/${{ github.actor }}/frontend:latest

      - name: Success
        run: echo "Release success"
